version: "3.7"

services:
  postgres:
    image: mdillon/postgis:11-alpine
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
      - "./server/scripts/tables.sql:/docker-entrypoint-initdb.d/tables.sql"
    env_file:
      - .env

  pgweb:
    image: sosedoff/pgweb
    ports: 
      - "8081:8081"
    links:
      - "postgres:postgres"
    depends_on:
      - "postgres"
    environment:
      - "DATABASE_URL=postgres://${PGUSER}:${PGPASSWORD}@postgres:${PGPORT}/${PGDATABASE}?sslmode=disable"

volumes:
  postgres_data:

